/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/admin/cigar-comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminCigarCommentRowDtoPaginatedResult'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/cigar-comments/{id}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/cigar-comments/{id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/cigar-images': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Все загруженные изображения каталога и коллекций (таблица CigarImages, внешнее хранилище). */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['PagedCigarImagesAdminResponse'];
            'application/json': components['schemas']['PagedCigarImagesAdminResponse'];
            'text/json': components['schemas']['PagedCigarImagesAdminResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/review-comments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminReviewCommentRowDtoPaginatedResult'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/review-comments/{id}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/review-comments/{id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/reviews/deleted': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Список обзоров, мягко удалённых авторами (для восстановления). */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdminDeletedReviewRowDtoPaginatedResult'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/reviews/{id}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Восстановить обзор (снять мягкое удаление). */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Список пользователей (пагинация и поиск по имени или email). */
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          search?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['PagedAdminUsersResponse'];
            'application/json': components['schemas']['PagedAdminUsersResponse'];
            'text/json': components['schemas']['PagedAdminUsersResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/users/{userId}/role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Изменение роли пользователя. При смене своей роли клиент должен передать confirmSelfChange после подтверждения в UI; в ответе может быть newToken. */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateUserRoleRequest'];
          'text/json': components['schemas']['UpdateUserRoleRequest'];
          'application/*+json': components['schemas']['UpdateUserRoleRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['UpdateUserRoleResponse'];
            'application/json': components['schemas']['UpdateUserRoleResponse'];
            'text/json': components['schemas']['UpdateUserRoleResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['ProblemDetails'];
            'application/json': components['schemas']['ProblemDetails'];
            'text/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Регистрирует нового пользователя */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Данные для регистрации */
      requestBody?: {
        content: {
          'application/json': components['schemas']['RegisterRequest'];
          'text/json': components['schemas']['RegisterRequest'];
          'application/*+json': components['schemas']['RegisterRequest'];
        };
      };
      responses: {
        /** @description Регистрация успешна */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
        /** @description Ошибка валидации или пользователь уже существует */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Too Many Requests */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Авторизует пользователя и выдает JWT токен */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Учетные данные для входа */
      requestBody?: {
        content: {
          'application/json': components['schemas']['LoginRequest'];
          'text/json': components['schemas']['LoginRequest'];
          'application/*+json': components['schemas']['LoginRequest'];
        };
      };
      responses: {
        /** @description Авторизация успешна */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
        /** @description Некорректные учетные данные */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Too Many Requests */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Выдаёт новый JWT по действующему Bearer-токену (продление сессии при повторном открытии клиента). */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AuthResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Too Many Requests */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Brands': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['BrandDto'][];
            'application/json': components['schemas']['BrandDto'][];
            'text/json': components['schemas']['BrandDto'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateBrandRequest'];
          'text/json': components['schemas']['CreateBrandRequest'];
          'application/*+json': components['schemas']['CreateBrandRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['BrandDto'];
            'application/json': components['schemas']['BrandDto'];
            'text/json': components['schemas']['BrandDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Brands/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['BrandDto'];
            'application/json': components['schemas']['BrandDto'];
            'text/json': components['schemas']['BrandDto'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateBrandRequest'];
          'text/json': components['schemas']['UpdateBrandRequest'];
          'application/*+json': components['schemas']['UpdateBrandRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['BrandDto'];
            'application/json': components['schemas']['BrandDto'];
            'text/json': components['schemas']['BrandDto'];
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/CigarComments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Список комментариев к справочной сигаре или к чужой записи в публичной коллекции. */
    get: {
      parameters: {
        query?: {
          cigarBaseId?: number;
          userCigarId?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CigarCommentDto'][];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateCigarCommentRequest'];
          'text/json': components['schemas']['CreateCigarCommentRequest'];
          'application/*+json': components['schemas']['CreateCigarCommentRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CigarCommentDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/CigarComments/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/CigarImages/upload-by-url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Скачивает изображение по URL и сохраняет (любой авторизованный пользователь). */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UploadCigarImageByUrlRequest'];
          'text/json': components['schemas']['UploadCigarImageByUrlRequest'];
          'application/*+json': components['schemas']['UploadCigarImageByUrlRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/CigarImages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          cigarBaseId?: number;
          userCigarId?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarImageDto'][];
            'application/json': components['schemas']['CigarImageDto'][];
            'text/json': components['schemas']['CigarImageDto'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateCigarImageRequest'];
          'text/json': components['schemas']['CreateCigarImageRequest'];
          'application/*+json': components['schemas']['CreateCigarImageRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarImageDto'];
            'application/json': components['schemas']['CigarImageDto'];
            'text/json': components['schemas']['CigarImageDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/CigarImages/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarImageDto'];
            'application/json': components['schemas']['CigarImageDto'];
            'text/json': components['schemas']['CigarImageDto'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateCigarImageRequest'];
          'text/json': components['schemas']['UpdateCigarImageRequest'];
          'application/*+json': components['schemas']['UpdateCigarImageRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/CigarImages/{id}/data': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Отдаёт бинарные данные полного изображения. CigarBase-изображения публичны; UserCigar — только владелец или staff. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/CigarImages/{id}/thumbnail': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Отдаёт миниатюру изображения (WebP, 320×320 max). CigarBase-изображения публичны; UserCigar — только владелец или staff. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/CigarImages/{id}/set-main': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  '/api/Cigars': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarResponseDto'][];
            'application/json': components['schemas']['CigarResponseDto'][];
            'text/json': components['schemas']['CigarResponseDto'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateCigarRequest'];
          'text/json': components['schemas']['CreateCigarRequest'];
          'application/*+json': components['schemas']['CreateCigarRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarResponseDto'];
            'application/json': components['schemas']['CigarResponseDto'];
            'text/json': components['schemas']['CigarResponseDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Cigars/bases': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          search?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarBaseDto'][];
            'application/json': components['schemas']['CigarBaseDto'][];
            'text/json': components['schemas']['CigarBaseDto'][];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'multipart/form-data': {
            Name: string;
            /** Format: int32 */
            BrandId: number;
            Country?: string;
            Description?: string;
            Strength?: string;
            /** Format: int32 */
            LengthMm?: number;
            /** Format: int32 */
            Diameter?: number;
            Wrapper?: string;
            Binder?: string;
            Filler?: string;
            /** @description Загружаемые файлы изображений. */
            NewImages?: components['schemas']['NewImageUpload'][];
            /** @description URL изображений (http/https); скачиваются на сервере и привязываются к карточке после CigarHelper.Api.Models.CreateCigarBaseFormRequest.NewImages. */
            ImageUrls?: string[];
            /** @description Главный кадр по индексу в CigarHelper.Api.Models.CreateCigarBaseFormRequest.ImageUrls (длина может быть меньше списка URL). */
            ImageUrlIsMain?: boolean[];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarBaseDto'];
            'application/json': components['schemas']['CigarBaseDto'];
            'text/json': components['schemas']['CigarBaseDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Cigars/bases/paginated': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: {
          page?: number;
          pageSize?: number;
          sortField?: string;
          sortOrder?: string;
          search?: string;
          brandId?: number;
          strength?: string;
          minReviewBody?: number;
          maxReviewBody?: number;
          minReviewAroma?: number;
          maxReviewAroma?: number;
          minReviewPairings?: number;
          maxReviewPairings?: number;
          minReviewScoredCount?: number;
          excludeBinaryMedia?: boolean;
          unmoderatedOnly?: boolean;
          withoutImagesOnly?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarBaseDtoPaginatedResult'];
            'application/json': components['schemas']['CigarBaseDtoPaginatedResult'];
            'text/json': components['schemas']['CigarBaseDtoPaginatedResult'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Cigars/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarResponseDto'];
            'application/json': components['schemas']['CigarResponseDto'];
            'text/json': components['schemas']['CigarResponseDto'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UserCigarUpdateRequest'];
          'text/json': components['schemas']['UserCigarUpdateRequest'];
          'application/*+json': components['schemas']['UserCigarUpdateRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarResponseDto'];
            'application/json': components['schemas']['CigarResponseDto'];
            'text/json': components['schemas']['CigarResponseDto'];
          };
        };
      };
    };
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Cigars/brands': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['BrandDto'][];
            'application/json': components['schemas']['BrandDto'][];
            'text/json': components['schemas']['BrandDto'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Cigars/{id}/smoked': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['MarkCigarSmokedRequest'];
          'text/json': components['schemas']['MarkCigarSmokedRequest'];
          'application/*+json': components['schemas']['MarkCigarSmokedRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarResponseDto'];
            'application/json': components['schemas']['CigarResponseDto'];
            'text/json': components['schemas']['CigarResponseDto'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Cigars/bases/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarBaseDto'];
            'application/json': components['schemas']['CigarBaseDto'];
            'text/json': components['schemas']['CigarBaseDto'];
          };
        };
      };
    };
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'multipart/form-data': {
            Name: string;
            /** Format: int32 */
            BrandId: number;
            Country?: string;
            Description?: string;
            Strength?: string;
            /** Format: int32 */
            LengthMm?: number;
            /** Format: int32 */
            Diameter?: number;
            Wrapper?: string;
            Binder?: string;
            Filler?: string;
            /** @description Новые загружаемые файлы изображений. */
            NewImages?: components['schemas']['NewImageUpload'][];
            /** @description Обновление IsMain для существующих изображений. */
            ExistingImages?: components['schemas']['ExistingImageUpdate'][];
            /** @description ID изображений для удаления (имя соответствует полю FormData на фронте). */
            ImageIdsToDelete?: number[];
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['CigarBaseDto'];
            'application/json': components['schemas']['CigarBaseDto'];
            'text/json': components['schemas']['CigarBaseDto'];
          };
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Dashboard/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Возвращает сводную информацию по коллекции текущего пользователя. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Успешно возвращена сводка по коллекции пользователя */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DashboardSummaryDto'];
          };
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Humidors': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получает список всех хьюмидоров текущего пользователя */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Успешное получение списка хьюмидоров */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HumidorResponseDto'][];
          };
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    put?: never;
    /** Создает новый хьюмидор */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Данные хьюмидора */
      requestBody?: {
        content: {
          'application/json': components['schemas']['HumidorCreateDto'];
          'text/json': components['schemas']['HumidorCreateDto'];
          'application/*+json': components['schemas']['HumidorCreateDto'];
        };
      };
      responses: {
        /** @description Хьюмидор успешно создан */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HumidorResponseDto'];
          };
        };
        /** @description Некорректные данные */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Humidors/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получает детальную информацию о хьюмидоре по ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID хьюмидора */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Хьюмидор найден */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HumidorDetailResponseDto'];
          };
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Хьюмидор не найден */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    /** Обновляет существующий хьюмидор */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID хьюмидора */
          id: number;
        };
        cookie?: never;
      };
      /** @description Новые данные хьюмидора */
      requestBody?: {
        content: {
          'application/json': components['schemas']['HumidorUpdateDto'];
          'text/json': components['schemas']['HumidorUpdateDto'];
          'application/*+json': components['schemas']['HumidorUpdateDto'];
        };
      };
      responses: {
        /** @description Хьюмидор успешно обновлен */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Некорректные данные */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Хьюмидор не найден */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    post?: never;
    /** Удаляет хьюмидор */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID хьюмидора */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Хьюмидор успешно удален */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Хьюмидор не найден */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Humidors/{humidorId}/cigars/{cigarId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Добавляет сигару в хьюмидор */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID хьюмидора */
          humidorId: number;
          /** @description ID сигары */
          cigarId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Сигара успешно добавлена в хьюмидор */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Ошибка при добавлении (например, превышена вместимость) */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    /** Удаляет сигару из хьюмидора */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID хьюмидора */
          humidorId: number;
          /** @description ID сигары */
          cigarId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Сигара успешно удалена из хьюмидора */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Сигара не найдена в указанном хьюмидоре */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Humidors/{humidorId}/cigars': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получает список сигар в хьюмидоре */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID хьюмидора */
          humidorId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Успешное получение списка сигар */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CigarBriefDto'][];
          };
        };
        /** @description Пользователь не авторизован */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MyProfileDto'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateProfileRequest'];
          'text/json': components['schemas']['UpdateProfileRequest'];
          'application/*+json': components['schemas']['UpdateProfileRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['UpdateProfileResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/Profile/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ChangePasswordRequest'];
          'text/json': components['schemas']['ChangePasswordRequest'];
          'application/*+json': components['schemas']['ChangePasswordRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ChangePasswordResponse'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ChangePasswordResponse'];
          };
        };
        /** @description Too Many Requests */
        429: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ChangePasswordResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Profile/avatar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Загрузка аватара (JPEG/PNG/WebP/AVIF/GIF), сохраняется как WebP до 384 px по длинной стороне. */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'multipart/form-data': {
            /** Format: binary */
            file?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MyProfileDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    /** Удалить загруженный аватар (внешний URL в поле не трогаем — только сброс ключа в хранилище). */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MyProfileDto'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/public/users/{username}/visibility': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          username: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PublicProfileVisibilityDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/public/users/{username}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          username: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PublicProfileDto'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/public/users/{username}/humidors/{humidorId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          username: string;
          humidorId: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HumidorDetailResponseDto'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ReviewComments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Список одобренных комментариев к обзору (только не удалённые обзоры). */
    get: {
      parameters: {
        query?: {
          reviewId?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReviewCommentDto'][];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateReviewCommentRequest'];
          'text/json': components['schemas']['CreateReviewCommentRequest'];
          'application/*+json': components['schemas']['CreateReviewCommentRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReviewCommentDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/ReviewComments/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Reviews': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получает список всех обзоров */
    get: {
      parameters: {
        query?: {
          /** @description Фильтр по пользователю (опционально) */
          userId?: number;
          /** @description Фильтр по сигаре (опционально) */
          cigarId?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReviewListItemDto'][];
          };
        };
      };
    };
    put?: never;
    /** Создает новый обзор */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Данные для создания обзора */
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateReviewRequest'];
          'text/json': components['schemas']['CreateReviewRequest'];
          'application/*+json': components['schemas']['CreateReviewRequest'];
        };
      };
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReviewDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Reviews/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получает детальную информацию об обзоре по его ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID обзора */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReviewDto'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    /** Обновляет существующий обзор */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID обзора */
          id: number;
        };
        cookie?: never;
      };
      /** @description Данные для обновления обзора */
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateReviewRequest'];
          'text/json': components['schemas']['UpdateReviewRequest'];
          'application/*+json': components['schemas']['UpdateReviewRequest'];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ReviewDto'];
          };
        };
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    post?: never;
    /** Мягкое удаление обзора автором (строка остаётся в БД, публично не отображается; восстановление — staff через `/api/admin/reviews/.../restore`). */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description ID обзора */
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ProblemDetails'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/Search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Глобальный поиск по сигарам пользователя, хьюмидорам, базе сигар и брендам.
     *     Минимальная длина запроса — 2 символа; результаты ограничены параметром limit (default 5, max 10).
     */
    get: {
      parameters: {
        query?: {
          q?: string;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'text/plain': components['schemas']['GlobalSearchResultDto'];
            'application/json': components['schemas']['GlobalSearchResultDto'];
            'text/json': components['schemas']['GlobalSearchResultDto'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/users/{id}/avatar': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AdminCigarCommentRowDto: {
      /** Format: int32 */
      id?: number;
      body?: string | null;
      /** Format: date-time */
      createdAt?: string;
      authorUsername?: string | null;
      isAuthorProfilePublic?: boolean;
      /** Format: int32 */
      cigarBaseId?: number | null;
      /** Format: int32 */
      userCigarId?: number | null;
      targetSummary?: string | null;
    };
    AdminCigarCommentRowDtoPaginatedResult: {
      items?: components['schemas']['AdminCigarCommentRowDto'][] | null;
      /** Format: int32 */
      totalCount?: number;
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    AdminDeletedReviewRowDto: {
      /** Format: int32 */
      id?: number;
      title?: string | null;
      /** Format: int32 */
      userId?: number;
      username?: string | null;
      isAuthorProfilePublic?: boolean;
      /** Format: int32 */
      cigarBaseId?: number;
      cigarName?: string | null;
      cigarBrand?: string | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      deletedAt?: string | null;
    };
    AdminDeletedReviewRowDtoPaginatedResult: {
      items?: components['schemas']['AdminDeletedReviewRowDto'][] | null;
      /** Format: int32 */
      totalCount?: number;
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    AdminReviewCommentRowDto: {
      /** Format: int32 */
      id?: number;
      body?: string | null;
      /** Format: date-time */
      createdAt?: string;
      authorUsername?: string | null;
      isAuthorProfilePublic?: boolean;
      /** Format: int32 */
      reviewId?: number;
      targetSummary?: string | null;
    };
    AdminReviewCommentRowDtoPaginatedResult: {
      items?: components['schemas']['AdminReviewCommentRowDto'][] | null;
      /** Format: int32 */
      totalCount?: number;
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    AdminUserListItemDto: {
      /** Format: int32 */
      id?: number;
      username?: string | null;
      email?: string | null;
      role?: components['schemas']['Role'];
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      lastLogin?: string | null;
    };
    AuthResponse: {
      success?: boolean;
      message?: string | null;
      token?: string | null;
      username?: string | null;
      /** Format: date-time */
      expiration?: string;
      role?: components['schemas']['Role'];
    };
    BrandBreakdownItemDto: {
      /** Format: int32 */
      brandId?: number;
      brandName: string;
      /** Format: int32 */
      cigarCount?: number;
      /** Format: double */
      averageRating?: number | null;
    };
    BrandDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      country?: string | null;
      description?: string | null;
      /** Format: byte */
      logoBytes?: string | null;
      isModerated?: boolean;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string | null;
    };
    ChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
      confirmNewPassword: string;
    };
    ChangePasswordResponse: {
      success?: boolean;
      message?: string | null;
      /** Format: int32 */
      retryAfterSeconds?: number | null;
    };
    CigarBaseDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      isModerated?: boolean;
      brand?: components['schemas']['BrandDto'];
      /** Format: int32 */
      lengthMm?: number | null;
      /** Format: int32 */
      diameter?: number | null;
      strength?: string | null;
      country?: string | null;
      description?: string | null;
      wrapper?: string | null;
      binder?: string | null;
      filler?: string | null;
      images?: components['schemas']['CigarImageDto'][] | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string | null;
      /** Format: double */
      reviewAvgBodyStrength?: number | null;
      /** Format: double */
      reviewAvgAromaScore?: number | null;
      /** Format: double */
      reviewAvgPairingsScore?: number | null;
      /** Format: int32 */
      reviewScoredReviewCount?: number;
    };
    CigarBaseDtoPaginatedResult: {
      items?: components['schemas']['CigarBaseDto'][] | null;
      /** Format: int32 */
      totalCount?: number;
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageSize?: number;
      /** Format: int32 */
      totalPages?: number;
    };
    CigarBriefDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      brand?: components['schemas']['BrandDto'];
      brandName?: string | null;
      /** Format: int32 */
      lengthMm?: number | null;
      /** Format: int32 */
      diameter?: number | null;
      strength?: string | null;
      /** Format: double */
      price?: number | null;
      /** Format: int32 */
      rating?: number | null;
      /** Format: int32 */
      quantity?: number;
      imageUrl?: string | null;
    };
    CigarCommentDto: {
      /** Format: int32 */
      id?: number;
      body?: string | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: int32 */
      authorUserId?: number;
      authorUsername?: string | null;
      isAuthorProfilePublic?: boolean;
      /** Format: int32 */
      cigarBaseId?: number | null;
      /** Format: int32 */
      userCigarId?: number | null;
      moderationStatus?: components['schemas']['CigarCommentModerationStatus'];
    };
    /** @enum {string} */
    CigarCommentModerationStatus: 'Pending' | 'Approved' | 'Rejected';
    CigarImageDto: {
      /** Format: int32 */
      id?: number;
      fileName?: string | null;
      contentType?: string | null;
      /** Format: int64 */
      fileSize?: number | null;
      description?: string | null;
      isMain?: boolean;
      /** Format: int32 */
      cigarBaseId?: number | null;
      /** Format: int32 */
      userCigarId?: number | null;
      /** Format: date-time */
      createdAt?: string;
      hasThumbnail?: boolean;
    };
    CigarResponseDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      brand?: components['schemas']['BrandDto'];
      brandName?: string | null;
      /** Format: int32 */
      lengthMm?: number | null;
      /** Format: int32 */
      diameter?: number | null;
      strength?: string | null;
      /** Format: double */
      price?: number | null;
      /** Format: int32 */
      rating?: number | null;
      /** Format: int32 */
      quantity?: number;
      imageUrl?: string | null;
      /** Format: int32 */
      cigarBaseId?: number;
      country?: string | null;
      description?: string | null;
      wrapper?: string | null;
      binder?: string | null;
      filler?: string | null;
      /** Format: int32 */
      humidorId?: number | null;
      humidor?: components['schemas']['HumidorDto'];
      /** Format: int32 */
      userId?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string | null;
      /** Format: date-time */
      purchasedAt?: string;
      /** Format: date-time */
      smokedAt?: string | null;
      /** Format: date-time */
      lastTouchedAt?: string;
      readonly isSmoked?: boolean;
      taste?: string | null;
      aroma?: string | null;
      images?: components['schemas']['CigarImageDto'][] | null;
    };
    CigarTimelinePointDto: {
      period: string;
      /** Format: int32 */
      purchasedCount?: number;
      /** Format: int32 */
      smokedCount?: number;
    };
    CreateBrandRequest: {
      name: string;
      country?: string | null;
      description?: string | null;
      logoUrl?: string | null;
      isModerated?: boolean;
    };
    CreateCigarCommentRequest: {
      /** Format: int32 */
      cigarBaseId?: number | null;
      /** Format: int32 */
      userCigarId?: number | null;
      body: string;
    };
    CreateCigarImageRequest: {
      fileName?: string | null;
      contentType?: string | null;
      /** Format: int64 */
      fileSize?: number | null;
      /** Format: byte */
      imageData?: string | null;
      description?: string | null;
      isMain?: boolean;
      /** Format: int32 */
      cigarBaseId?: number | null;
      /** Format: int32 */
      userCigarId?: number | null;
    };
    CreateCigarRequest: {
      /** Format: int32 */
      cigarBaseId: number;
      /** Format: double */
      price?: number | null;
      /** Format: int32 */
      humidorId?: number | null;
      taste?: string | null;
      aroma?: string | null;
      /** Format: int32 */
      rating?: number | null;
      /** Format: int32 */
      quantity?: number | null;
      imageUrl?: string | null;
      imageUrls?: string[] | null;
    };
    CreateReviewCommentRequest: {
      /** Format: int32 */
      reviewId: number;
      body: string;
    };
    CreateReviewImageRequest: {
      imageUrl: string;
      caption?: string | null;
    };
    CreateReviewRequest: {
      title: string;
      content: string;
      /** Format: int32 */
      rating: number;
      /** Format: int32 */
      cigarId: number;
      smokingExperience?: string | null;
      aroma?: string | null;
      taste?: string | null;
      /** Format: int32 */
      construction?: number | null;
      /** Format: int32 */
      burnQuality?: number | null;
      /** Format: int32 */
      draw?: number | null;
      venue?: string | null;
      /** Format: date-time */
      smokingDate?: string | null;
      /** Format: int32 */
      smokingDurationMinutes?: number | null;
      /** Format: int32 */
      bodyStrengthScore?: number | null;
      /** Format: int32 */
      aromaScore?: number | null;
      /** Format: int32 */
      pairingsScore?: number | null;
      images?: components['schemas']['CreateReviewImageRequest'][] | null;
    };
    DashboardSummaryDto: {
      /** Format: int32 */
      totalHumidors?: number;
      /** Format: int32 */
      totalCigars?: number;
      /** Format: int32 */
      totalCapacity?: number;
      /** Format: double */
      averageFillPercent?: number;
      /** Format: int32 */
      averageDaysToSmoke?: number;
      /** Format: double */
      averageCigarRating?: number | null;
      brandBreakdown?: components['schemas']['BrandBreakdownItemDto'][] | null;
      recentReviews?: components['schemas']['RecentReviewDto'][] | null;
      timeline?: components['schemas']['CigarTimelinePointDto'][] | null;
      staleCigarReminders?: components['schemas']['StaleCigarReminderDto'][] | null;
    };
    /** @description Обновление флага IsMain для существующего изображения. */
    ExistingImageUpdate: {
      /** Format: int32 */
      id?: number;
      isMain?: boolean;
    };
    GlobalSearchResultDto: {
      cigars?: components['schemas']['SearchCigarDto'][] | null;
      humidors?: components['schemas']['SearchHumidorDto'][] | null;
      cigarBases?: components['schemas']['SearchCigarBaseDto'][] | null;
      brands?: components['schemas']['SearchBrandDto'][] | null;
    };
    HumidorCreateDto: {
      name: string;
      description?: string | null;
      /** Format: int32 */
      capacity: number;
      /** Format: int32 */
      humidity?: number | null;
    };
    HumidorDetailResponseDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      description?: string | null;
      /** Format: int32 */
      capacity?: number;
      /** Format: int32 */
      humidity?: number | null;
      cigars?: components['schemas']['CigarBriefDto'][] | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string | null;
    };
    HumidorDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      description?: string | null;
      /** Format: int32 */
      capacity?: number;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string | null;
    };
    HumidorResponseDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      description?: string | null;
      /** Format: int32 */
      capacity?: number;
      /** Format: int32 */
      currentCount?: number;
      /** Format: int32 */
      humidity?: number | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string | null;
    };
    HumidorUpdateDto: {
      name: string;
      description?: string | null;
      /** Format: int32 */
      capacity: number;
      /** Format: int32 */
      humidity?: number | null;
    };
    LoginRequest: {
      username: string;
      password: string;
    };
    MarkCigarSmokedRequest: {
      /** Format: date-time */
      smokedAt?: string | null;
    };
    MyProfileDto: {
      /** Format: int32 */
      id?: number;
      username?: string | null;
      email?: string | null;
      role?: components['schemas']['Role'];
      isProfilePublic?: boolean;
      /** @description Внешний URL или относительный путь `/api/users/{id}/avatar` для загруженного файла. */
      avatarUrl?: string | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      lastLogin?: string | null;
    };
    /** @description Один загружаемый файл изображения в составе multipart-запроса. */
    NewImageUpload: {
      /** Format: binary */
      file?: string | null;
      isMain?: boolean;
    };
    PagedAdminUsersResponse: {
      items?: components['schemas']['AdminUserListItemDto'][] | null;
      /** Format: int32 */
      totalCount?: number;
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageSize?: number;
    };
    /** @description Пагинированный список изображений сигар (хранилище MinIO/LocalFile) для админ-панели. */
    PagedCigarImagesAdminResponse: {
      items?: components['schemas']['CigarImageDto'][] | null;
      /** Format: int32 */
      totalCount?: number;
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      pageSize?: number;
    };
    ProblemDetails: {
      type?: string | null;
      title?: string | null;
      /** Format: int32 */
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
    } & {
      [key: string]: unknown;
    };
    PublicProfileDto: {
      username?: string | null;
      /** @description Внешний URL или `/api/users/{id}/avatar`. */
      avatarUrl?: string | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      lastLogin?: string | null;
      humidors?: components['schemas']['HumidorResponseDto'][] | null;
    };
    /**
     * @description Лёгкий ответ для префетча: виден ли публичный профиль (пользователь есть и IsProfilePublic).
     *     Не различает «нет пользователя» и «профиль закрыт» — в обоих случаях IsVisible = false.
     */
    PublicProfileVisibilityDto: {
      isVisible?: boolean;
    };
    RecentReviewDto: {
      /** Format: int32 */
      id?: number;
      title: string;
      cigarName: string;
      cigarBrand: string;
      /** Format: int32 */
      rating?: number;
      /** Format: date-time */
      createdAt?: string;
      username: string;
      isAuthorProfilePublic?: boolean;
      userAvatarUrl?: string | null;
    };
    RegisterRequest: {
      username: string;
      password: string;
      confirmPassword: string;
      confirmedAge18?: boolean;
    };
    ReviewCommentDto: {
      /** Format: int32 */
      id?: number;
      /** Format: int32 */
      reviewId?: number;
      body?: string | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: int32 */
      authorUserId?: number;
      authorUsername?: string | null;
      isAuthorProfilePublic?: boolean;
      moderationStatus?: components['schemas']['CigarCommentModerationStatus'];
    };
    ReviewDto: {
      /** Format: int32 */
      id?: number;
      title?: string | null;
      content?: string | null;
      /** Format: int32 */
      rating?: number;
      /** Format: int32 */
      userId?: number;
      username?: string | null;
      isAuthorProfilePublic?: boolean;
      userAvatarUrl?: string | null;
      /** Format: int32 */
      cigarId?: number;
      cigarName?: string | null;
      cigarBrand?: string | null;
      cigarCountry?: string | null;
      /** Format: int32 */
      cigarLengthMm?: number | null;
      /** Format: int32 */
      cigarDiameter?: number | null;
      cigarWrapper?: string | null;
      cigarBinder?: string | null;
      cigarFiller?: string | null;
      images?: components['schemas']['ReviewImageDto'][] | null;
      smokingExperience?: string | null;
      aroma?: string | null;
      taste?: string | null;
      /** Format: int32 */
      construction?: number | null;
      /** Format: int32 */
      burnQuality?: number | null;
      /** Format: int32 */
      draw?: number | null;
      venue?: string | null;
      /** Format: int32 */
      bodyStrengthScore?: number | null;
      /** Format: int32 */
      aromaScore?: number | null;
      /** Format: int32 */
      pairingsScore?: number | null;
      /** Format: date-time */
      smokingDate?: string;
      /** Format: int32 */
      smokingDurationMinutes?: number | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string | null;
    };
    ReviewImageDto: {
      /** Format: int32 */
      id?: number;
      /** Format: byte */
      imageBytes?: string | null;
      caption?: string | null;
    };
    ReviewListItemDto: {
      /** Format: int32 */
      id?: number;
      title?: string | null;
      summary?: string | null;
      /** Format: int32 */
      rating?: number;
      /** Format: int32 */
      userId?: number;
      username?: string | null;
      isAuthorProfilePublic?: boolean;
      userAvatarUrl?: string | null;
      cigarName?: string | null;
      cigarBrand?: string | null;
      /** Format: byte */
      mainImageBytes?: string | null;
      /** Format: int32 */
      imageCount?: number;
      /** Format: date-time */
      createdAt?: string;
    };
    /** @enum {string} */
    Role: 'User' | 'Moderator' | 'Admin';
    SearchBrandDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      country?: string | null;
    };
    SearchCigarBaseDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      brandName?: string | null;
    };
    SearchCigarDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      brandName?: string | null;
      humidorName?: string | null;
    };
    SearchHumidorDto: {
      /** Format: int32 */
      id?: number;
      name?: string | null;
      description?: string | null;
    };
    StaleCigarReminderDto: {
      /** Format: int32 */
      cigarId?: number;
      cigarName: string;
      brandName: string;
      /** Format: int32 */
      daysUntouched?: number;
      /** Format: date-time */
      lastTouchedAt?: string;
    };
    UpdateBrandRequest: {
      name: string;
      country?: string | null;
      description?: string | null;
      logoUrl?: string | null;
      isModerated?: boolean;
    };
    UpdateCigarImageRequest: {
      fileName?: string | null;
      contentType?: string | null;
      /** Format: int64 */
      fileSize?: number | null;
      /** Format: byte */
      imageData?: string | null;
      description?: string | null;
      isMain?: boolean | null;
    };
    UpdateProfileRequest: {
      username: string;
      /** Format: email */
      email?: string | null;
      isProfilePublic?: boolean;
    };
    UpdateProfileResponse: {
      success?: boolean;
      message?: string | null;
      profile?: components['schemas']['MyProfileDto'];
      newToken?: string | null;
    };
    UpdateReviewRequest: {
      title: string;
      content: string;
      /** Format: int32 */
      rating: number;
      smokingExperience?: string | null;
      aroma?: string | null;
      taste?: string | null;
      /** Format: int32 */
      construction?: number | null;
      /** Format: int32 */
      burnQuality?: number | null;
      /** Format: int32 */
      draw?: number | null;
      venue?: string | null;
      /** Format: date-time */
      smokingDate?: string | null;
      /** Format: int32 */
      smokingDurationMinutes?: number | null;
      /** Format: int32 */
      bodyStrengthScore?: number | null;
      /** Format: int32 */
      aromaScore?: number | null;
      /** Format: int32 */
      pairingsScore?: number | null;
      imagesToAdd?: components['schemas']['CreateReviewImageRequest'][] | null;
      imageIdsToRemove?: number[] | null;
    };
    UpdateUserRoleRequest: {
      role: components['schemas']['Role'];
      /** @description Обязателен при смене собственной роли (после явного подтверждения в UI). */
      confirmSelfChange?: boolean;
    };
    UpdateUserRoleResponse: {
      success?: boolean;
      message?: string | null;
      /** @description Новый JWT при смене своей роли; иначе null. */
      newToken?: string | null;
    };
    UploadCigarImageByUrlRequest: {
      url: string;
      /** Format: int32 */
      cigarBaseId?: number | null;
    };
    UserCigarUpdateRequest: {
      /** Format: double */
      price?: number | null;
      /** Format: int32 */
      humidorId?: number | null;
      taste?: string | null;
      aroma?: string | null;
      /** Format: int32 */
      rating?: number | null;
      /** Format: int32 */
      quantity?: number;
      imageUrl?: string | null;
      imageUrlsToAdd?: string[] | null;
      imageIdsToRemove?: number[] | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
